CREATE TABLE "customers" (
  "customer_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_email" varchar NOT NULL,
  "customer_name" varchar NOT NULL,
  "updated_at" timestamp NOT NULL,
  "batch_id" int NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "parent_id" int NOT NULL,
  "updated_at" timestamp NOT NULL,
  "batch_id" int NOT NULL
);

CREATE TABLE "products" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category" int NOT NULL,
  "name" varchar NOT NULL,
  "price" numeric NOT NULL,
  "updated_at" timestamp NOT NULL,
  "batch_id" int NOT NULL
);

CREATE TABLE "orders" (
  "order_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_date" timestamp NOT NULL,
  "customer_id" int NOT NULL,
  "updated_at" timestamp NOT NULL,
  "batch_id" int NOT NULL
);

CREATE TABLE "order_status" (
  "order_id" int NOT NULL,
  "order_status" varchar NOT NULL,
  "updated_at" timestamp NOT NULL,
  "batch_id" int NOT NULL
);

CREATE TABLE "order_items" (
  "order_id" int NOT NULL,
  "product_id" int NOT NULL,
  "quantity" int NOT NULL CHECK (quantity >0),
  "gross_price" numeric NOT NULL,
  "discount" numeric NOT NULL CHECK ((discount >= 0) AND (discount <= gross_price)),
  "price_after_discount" numeric NOT NULL,
  "updated_at" timestamp NOT NULL,
  "batch_id" int NOT NULL
);

CREATE TABLE "payments" (
  "order_id" int NOT NULL,
  "customer_id" int NOT NULL,
  "price_after_discount" int NOT NULL,
  "payment_status" varchar NOT NULL,
  "payment_date" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL,
  "batch_id" int NOT NULL
);

CREATE UNIQUE INDEX ON "customers" ("updated_at", "batch_id");

CREATE UNIQUE INDEX ON "categories" ("updated_at", "batch_id");

CREATE UNIQUE INDEX ON "products" ("updated_at", "batch_id");

CREATE UNIQUE INDEX ON "orders" ("updated_at", "batch_id");

CREATE UNIQUE INDEX ON "order_status" ("updated_at", "batch_id");

CREATE UNIQUE INDEX ON "order_items" ("updated_at", "batch_id");

CREATE UNIQUE INDEX ON "payments" ("updated_at", "batch_id");

ALTER TABLE "payments" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("customer_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payments" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "products" ADD FOREIGN KEY ("category") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_status" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("customer_id") DEFERRABLE INITIALLY IMMEDIATE;
