CREATE TABLE IF NOT EXISTS "customers" (
  "customer_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_email" varchar NOT NULL,
  "customer_name" varchar NOT NULL,
  "updated_at" timestamp NOT NULL,
  "batch_id" int NOT NULL
);

CREATE TABLE IF NOT EXISTS "category" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "parent_id" int NOT NULL,
  "updated_at" timestamp NOT NULL,
  "batch_id" int NOT NULL
);

CREATE TABLE IF NOT EXISTS "product" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category" int NOT NULL,
  "name" varchar NOT NULL,
  "price" numeric NOT NULL,
  "updated_at" timestamp NOT NULL,
  "batch_id" int NOT NULL
);

CREATE TABLE IF NOT EXISTS "orders" (
  "order_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_date" timestamp NOT NULL,
  "customer_id" int NOT NULL,
  "updated_at" timestamp NOT NULL,
  "batch_id" int NOT NULL
);

CREATE TABLE IF NOT EXISTS "order_status" (
  "order_id" int NOT NULL,
  "order_status" varchar NOT NULL,
  "updated_at" timestamp NOT NULL,
  "batch_id" int NOT NULL
);

CREATE TABLE IF NOT EXISTS "order_item" (
  "order_id" int NOT NULL,
  "product_id" int NOT NULL,
  "quantity" int NOT NULL CHECK (quantity >0),
  "gross_price" numeric NOT NULL,
  "discount" numeric NOT NULL CHECK ((discount >= 0) AND (discount <= gross_price)),
  "price_after_discount" numeric NOT NULL,
  "updated_at" timestamp NOT NULL,
  "batch_id" int NOT NULL
);

CREATE TABLE IF NOT EXISTS "payment" (
  "order_id" int NOT NULL,
  "customer_id" int NOT NULL,
  "price_after_discount" int NOT NULL,
  "payment_status" varchar NOT NULL,
  "payment_date" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL,
  "batch_id" int NOT NULL
);

CREATE UNIQUE INDEX ON "customers" ("updated_at", "batch_id");

CREATE UNIQUE INDEX ON "category" ("updated_at", "batch_id");

CREATE UNIQUE INDEX ON "product" ("updated_at", "batch_id");

CREATE UNIQUE INDEX ON "orders" ("updated_at", "batch_id");

CREATE UNIQUE INDEX ON "order_status" ("updated_at", "batch_id");

CREATE UNIQUE INDEX ON "order_item" ("updated_at", "batch_id");

CREATE UNIQUE INDEX ON "payment" ("updated_at", "batch_id");

ALTER TABLE "payment" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("customer_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payment" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_item" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product" ADD FOREIGN KEY ("category") REFERENCES "category" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_item" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_status" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("customer_id") DEFERRABLE INITIALLY IMMEDIATE;
